// @ts-ignore
import ExcelJS from 'exceljs';
import { saveAs } from 'file-saver';

interface ExportData {
  reportDate: string;
  summary: {
    totalScreenings: number;
    atRiskPatients: number;
    activeReferrals: number;
    successRate: string;
  };
  screeningTrends: any[];
  ageDistribution: any[];
  severityData: any[];
  facilityPerformance: any[];
  serviceRequestData: any[];
}

export const generateProfessionalExcelReport = async (data: ExportData, filename: string) => {
  const workbook = new ExcelJS.Workbook();
  
  // Set Workbook Properties
  workbook.creator = 'NutriTrack System';
  workbook.lastModifiedBy = 'NutriTrack System';
  workbook.created = new Date();
  workbook.modified = new Date();

  const primaryColor = '10B981'; // Green
  const headerFontColor = 'FFFFFF';
  const alternatingRowColor = 'F9FAFB';

  // ---------------------------------------------------------
  // Sheet 1: Executive Summary
  // ---------------------------------------------------------
  const summarySheet = workbook.addWorksheet('Executive Summary', {
    pageSetup: { paperSize: 9, orientation: 'portrait' },
    headerFooter: {
      firstHeader: '&LNutriTrack System&C&BExecutive Summary&R&D',
      firstFooter: '&LConfidential&CPage &P of &N&RGenerated: &T'
    }
  });

  summarySheet.getColumn('A').width = 30;
  summarySheet.getColumn('B').width = 20;

  // Title
  summarySheet.mergeCells('A1:B2');
  const titleCell = summarySheet.getCell('A1');
  titleCell.value = 'NutriTrack Analytics Report';
  titleCell.font = { size: 16, bold: true, color: { argb: primaryColor } };
  titleCell.alignment = { vertical: 'middle', horizontal: 'center' };

  // Metadata
  summarySheet.getCell('A4').value = 'Reporting Period:';
  summarySheet.getCell('A4').font = { bold: true };
  summarySheet.getCell('B4').value = new Date(data.reportDate).toLocaleDateString();

  summarySheet.getCell('A5').value = 'Generated By:';
  summarySheet.getCell('A5').font = { bold: true };
  summarySheet.getCell('B5').value = 'NutriTrack Administrator';

  // Summary Metrics Section
  summarySheet.getCell('A7').value = 'Key Performance Indicators';
  summarySheet.getCell('A7').font = { size: 14, bold: true };

  const metrics = [
    { label: 'Total Screenings', value: data.summary.totalScreenings },
    { label: 'At-Risk Patients (MAM/SAM)', value: data.summary.atRiskPatients },
    { label: 'Active Referrals', value: data.summary.activeReferrals },
    { label: 'Resolution Success Rate', value: data.summary.successRate }
  ];

  metrics.forEach((m, index) => {
    const row = 9 + index;
    summarySheet.getCell(`A${row}`).value = m.label;
    summarySheet.getCell(`B${row}`).value = m.value;
    
    // Styling
    summarySheet.getCell(`A${row}`).border = {
      top: { style: 'thin' }, bottom: { style: 'thin' },
      left: { style: 'thin' }, right: { style: 'thin' }
    };
    summarySheet.getCell(`B${row}`).border = {
      top: { style: 'thin' }, bottom: { style: 'thin' },
      left: { style: 'thin' }, right: { style: 'thin' }
    };
    summarySheet.getCell(`A${row}`).fill = {
      type: 'pattern', pattern: 'solid', fgColor: { argb: 'E5E7EB' }
    };
    summarySheet.getCell(`B${row}`).alignment = { horizontal: 'right' };
    summarySheet.getCell(`B${row}`).font = { bold: true };
  });

  // ---------------------------------------------------------
  // Sheet 2: Facility Performance
  // ---------------------------------------------------------
  const facilitySheet = workbook.addWorksheet('Facility Performance', {
    pageSetup: { paperSize: 9, orientation: 'landscape' },
    views: [{ state: 'frozen', ySplit: 1 }],
    headerFooter: {
      firstHeader: '&LNutriTrack System&C&BFacility Performance&R&D',
      firstFooter: '&LConfidential&CPage &P of &N&RGenerated: &T'
    }
  });

  facilitySheet.columns = [
    { header: 'Facility Name', key: 'facility', width: 35 },
    { header: 'Normal Cases', key: 'normal', width: 15 },
    { header: 'MAM Cases', key: 'moderate', width: 15 },
    { header: 'SAM Cases', key: 'severe', width: 15 },
    { header: 'Total Screenings', key: 'total', width: 18 },
    { header: 'Assigned Doctors', key: 'doctors', width: 18 },
    { header: 'Assigned CHWs', key: 'chws', width: 18 }
  ];

  // Add Data
  data.facilityPerformance.forEach((row, index) => {
    const total = row.normal + row.moderate + row.severe;
    facilitySheet.addRow({ ...row, total });
  });

  // Style Header
  facilitySheet.getRow(1).eachCell((cell: any) => {
    cell.font = { bold: true, color: { argb: headerFontColor } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: primaryColor } };
    cell.alignment = { vertical: 'middle', horizontal: 'center' };
  });

  // Apply filters
  facilitySheet.autoFilter = {
    from: 'A1',
    to: { row: 1, column: facilitySheet.columns.length }
  };

  // Alternating Row Colors & Conditional Formatting
  facilitySheet.eachRow((row: any, rowNumber: number) => {
    if (rowNumber > 1) {
      if (rowNumber % 2 === 0) {
        row.eachCell((cell: any) => {
          cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: alternatingRowColor } };
        });
      }
      
      // Highlight severe cases (SAM > 0)
      const severeCell = row.getCell(4);
      if (typeof severeCell.value === 'number' && severeCell.value > 0) {
        severeCell.font = { color: { argb: 'EF4444' }, bold: true };
      }
    }
  });

  // ---------------------------------------------------------
  // Sheet 3: Analytics Data
  // ---------------------------------------------------------
  const analyticsSheet = workbook.addWorksheet('Analytics Data', {
    pageSetup: { paperSize: 9, orientation: 'portrait' }
  });

  analyticsSheet.getColumn('A').width = 25;
  analyticsSheet.getColumn('B').width = 15;
  analyticsSheet.getColumn('C').width = 15;
  analyticsSheet.getColumn('D').width = 15;

  // Screening Trends
  analyticsSheet.getCell('A1').value = 'Screening Trends';
  analyticsSheet.getCell('A1').font = { size: 12, bold: true };
  analyticsSheet.addRow(['Month', 'Normal', 'Moderate', 'Severe']);
  analyticsSheet.getRow(2).font = { bold: true };
  
  data.screeningTrends.forEach(item => {
    analyticsSheet.addRow([item.name, item.normal, item.moderate, item.severe]);
  });

  analyticsSheet.addRow([]); // Blank
  
  // Severity Distribution
  const currentRow = analyticsSheet.lastRow ? analyticsSheet.lastRow.number + 2 : 10;
  analyticsSheet.getCell(`A${currentRow}`).value = 'Malnutrition Severity Breakdown';
  analyticsSheet.getCell(`A${currentRow}`).font = { size: 12, bold: true };
  analyticsSheet.addRow(['Classification', 'Patient Count']);
  analyticsSheet.getRow(currentRow + 1).font = { bold: true };

  data.severityData.forEach(item => {
    analyticsSheet.addRow([item.name, item.value]);
  });

  // Save the workbook
  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  saveAs(blob, `${filename}_${new Date().toISOString().split('T')[0]}.xlsx`);
};
